### ISSUE TITLE
一个提议以及0.79的貌似bug

### ISSUE THREAD

**Issue by jimmyalxe** [LXG-Shadow/BiliAudioBot#1]
在播放空闲歌单时，如果用户点歌会立马切歌，能否设置选项，点歌后切歌或者当前歌曲播放结束后

**Comment by jimmyalxe** [comment]
另发现0.79的匹配顺序有问题了 原本只有VIP歌曲走 bilibili -> 酷我 -> 网易云  但是现在免费歌曲也走了这个线路 你的直播间的78版本正常。
该现象出现出现在播放空闲歌曲时。点歌时正常出现原版网易云歌曲。但是空闲歌单内的歌曲不行
出现问题JJ的歌曲 歌单为3113757800，出现问题歌曲 曹操

**Comment by jimmyalxe** [comment]
![捕获](https://user-images.githubusercontent.com/50981348/113418518-3bd63a80-93f8-11eb-94fa-1c272058df38.PNG)
出现问题截图
![捕获2](https://user-images.githubusercontent.com/50981348/113418585-5dcfbd00-93f8-11eb-884f-9f6ced17f7a4.PNG)
同一首歌点歌后

**Comment by aynakeya** [comment]
我看了一眼，歌单内的歌曲曹操为vip歌曲，因为闲置歌单点歌是直接使用音乐id进行的精确点歌，所以获取到的是vip歌曲，于是就会自动进行匹配。

![QQ截图20210403010953](https://user-images.githubusercontent.com/32156054/113437793-e27f0300-9419-11eb-96e8-438a130d6d90.png)

使用关键字点歌，调用的是网易云的搜索接口。有两首曹操，且第一首不是vip，所以选用的第一首歌会直接使用网易云源。

![QQ截图20210403011205](https://user-images.githubusercontent.com/32156054/113437811-ea3ea780-9419-11eb-8cbd-25bd998bc977.png)

![QQ截图20210403011212](https://user-images.githubusercontent.com/32156054/113437816-eca10180-9419-11eb-8d03-8f17105c3e8e.png)

期待爱，同理。

关于设置是否自动切歌，将于demo0.8.0 中加入

**Comment by jimmyalxe** [comment]
大概明白了歌名相同但似乎歌曲的id不同.
